In [2]:
BASE_DIR = "/teamspace/studios/this_studio/.porting"

In [10]:
import os
from safetensors.torch import load_file

model_path = os.path.join(BASE_DIR, "models", "loras", "comfyui_subject_lora16.safetensors")
weights = load_file(model_path)

for tensor in weights.values():
    tensor.requires_grad_()
    print(tensor.requires_grad_())

tensor(16., dtype=torch.bfloat16, requires_grad=True)
tensor([[-0.0080,  0.0012, -0.0125,  ...,  0.0031,  0.0042,  0.0149],
        [ 0.0022, -0.0080,  0.0042,  ...,  0.0204, -0.0006, -0.0107],
        [ 0.0068,  0.0043, -0.0089,  ..., -0.0008,  0.0057,  0.0024],
        ...,
        [ 0.0150,  0.0104,  0.0072,  ...,  0.0145,  0.0059,  0.0091],
        [ 0.0186,  0.0066,  0.0153,  ..., -0.0023,  0.0087,  0.0030],
        [-0.0074, -0.0198,  0.0109,  ..., -0.0178, -0.0082,  0.0181]],
       dtype=torch.bfloat16, requires_grad=True)
tensor([[ 0.0049, -0.0012,  0.0072,  ..., -0.0007,  0.0012, -0.0123],
        [-0.0085, -0.0040, -0.0025,  ..., -0.0044,  0.0014, -0.0042],
        [ 0.0265, -0.0280, -0.0020,  ...,  0.0069, -0.0265,  0.0112],
        ...,
        [-0.0306, -0.0192, -0.0068,  ..., -0.0156,  0.0248, -0.0488],
        [-0.0082,  0.0070, -0.0079,  ..., -0.0054, -0.0073, -0.0111],
        [-0.0017, -0.0029, -0.0004,  ..., -0.0028,  0.0014,  0.0058]],
       dtype=torch.bfloat16, 

tensor([[-0.0127, -0.0483, -0.0322,  ..., -0.0084, -0.0255,  0.0220],
        [ 0.0325,  0.0156,  0.0071,  ...,  0.0017,  0.0537, -0.0291],
        [-0.0266, -0.0165,  0.0128,  ..., -0.0234,  0.0063,  0.0206],
        ...,
        [-0.0010,  0.0078,  0.0150,  ...,  0.0197, -0.0197,  0.0038],
        [-0.0032,  0.0227, -0.0123,  ...,  0.0132,  0.0168,  0.0129],
        [ 0.0366, -0.0050,  0.0148,  ...,  0.0334,  0.0121,  0.0371]],
       dtype=torch.bfloat16, requires_grad=True)
tensor(16., dtype=torch.bfloat16, requires_grad=True)
tensor([[ 0.0026,  0.0164,  0.0144,  ..., -0.0075,  0.0146, -0.0066],
        [ 0.0172, -0.0175, -0.0145,  ...,  0.0020,  0.0058, -0.0176],
        [-0.0157,  0.0120,  0.0114,  ..., -0.0145,  0.0167, -0.0139],
        ...,
        [-0.0128,  0.0118, -0.0132,  ..., -0.0139,  0.0013, -0.0135],
        [-0.0079, -0.0067,  0.0175,  ...,  0.0098,  0.0172,  0.0038],
        [ 0.0063, -0.0073,  0.0179,  ...,  0.0092, -0.0081,  0.0096]],
       dtype=torch.bfloat16, 

In [11]:
import os
from safetensors.torch import load_file

model_path = os.path.join(BASE_DIR, "models", "unet", "flux1-fill-dev-fp8.safetensors")
weights = load_file(model_path)

for tensor in weights.values():
    tensor.requires_grad_()
    print(tensor.requires_grad_())

tensor([0.6875, 0.5625, 0.4688, 0.4375, 0.4062, 0.5625, 0.3750, 0.3125, 0.4375,
        0.4375, 0.5625, 0.3750, 0.3438, 0.3750, 0.4375, 0.3125, 0.5000, 0.4688,
        0.4688, 0.4688, 0.5000, 0.5625, 0.5000, 0.5625, 0.6250, 0.6250, 0.7500,
        0.5625, 0.6875, 0.6875, 0.6250, 0.7500, 0.6250, 0.7500, 0.6875, 0.5625,
        0.4375, 0.5625, 0.6875, 0.5625, 0.4062, 0.4688, 0.6250, 0.4688, 0.4062,
        0.5000, 0.2500, 0.4375, 0.4688, 0.4375, 0.6250, 0.6250, 0.3750, 0.4062,
        0.4062, 0.4375, 0.4062, 0.3750, 0.4375, 0.5625, 0.4375, 0.5000, 0.4375,
        0.4375, 0.5000, 0.4062, 0.4062, 0.4688, 0.4688, 0.4688, 0.4062, 0.4062,
        0.5000, 0.5000, 0.5000, 0.5000, 0.4688, 0.5000, 0.6250, 0.5000, 0.6875,
        0.6250, 0.6875, 0.7500, 0.6250, 0.6250, 0.6875, 0.7500, 0.7500, 0.6875,
        0.6875, 0.7500, 0.6250, 0.8125, 0.5000, 0.6250, 0.4375, 0.6250, 0.6250,
        0.4688, 0.6875, 0.2500, 0.5625, 0.4375, 0.4062, 0.2812, 0.3750, 0.5000,
        0.4375, 0.5625, 0.3125, 0.6875, 

tensor([[ 0.0312, -0.0117, -0.0176,  ..., -0.0117,  0.0547,  0.0020],
        [-0.0000,  0.0293, -0.0078,  ...,  0.0273,  0.0469,  0.0195],
        [-0.0059, -0.0547,  0.0273,  ..., -0.0312,  0.0938,  0.0117],
        ...,
        [-0.0078,  0.0273,  0.0273,  ..., -0.0117, -0.0391,  0.0391],
        [ 0.0078, -0.0039,  0.0938,  ...,  0.0293, -0.0078, -0.0059],
        [-0.0273, -0.0078, -0.0215,  ...,  0.0156,  0.0547,  0.0547]],
       dtype=torch.float8_e4m3fn, requires_grad=True)
tensor([-0.0215, -0.0156, -0.0078,  ...,  0.0352, -0.0293, -0.0293],
       dtype=torch.float8_e4m3fn, requires_grad=True)
tensor([[-0.0078, -0.0215, -0.0215,  ..., -0.0293,  0.0215, -0.0195],
        [-0.0254,  0.0703, -0.0137,  ..., -0.1172, -0.0391, -0.0039],
        [ 0.0273,  0.0117,  0.0625,  ..., -0.0234,  0.0098, -0.0547],
        ...,
        [ 0.0293,  0.0176,  0.0273,  ..., -0.0391, -0.0117, -0.0254],
        [ 0.0430,  0.0059, -0.0430,  ..., -0.0176,  0.0703, -0.0000],
        [-0.0195,  0.1094,

KeyboardInterrupt: 

In [5]:
import os
import torch
import re
from safetensors.torch import load_file
from copy import deepcopy

BASE_DIR = "/teamspace/studios/this_studio/.porting"

def load_flux_fill():
    model_path = os.path.join(BASE_DIR, "models", "unet", "flux1-fill-dev-fp8.safetensors")
    print(f"Loading base model: {os.path.basename(model_path)}\n")
    return load_file(model_path)

def translate_lora_key_to_model_key(lora_key):
    return re.sub(r'(_)(\d+)', r'.\2', lora_key)

if __name__ == "__main__":
    LORA_FILENAME = "comfyui_subject_lora16.safetensors"
    LORA_STRENGTH = 1.0

    base_weights = load_flux_fill()
    lora_path = os.path.join(BASE_DIR, "models", "loras", LORA_FILENAME)
    if not os.path.exists(lora_path):
        raise FileNotFoundError(f"LoRA not found at {lora_path}")
    
    print(f"Loading LoRA: {LORA_FILENAME}\n")
    lora_weights = load_file(lora_path)
    
    weights_with_loras = deepcopy(base_weights)

    print("--- Starting Layer-by-Layer Verification ---\n")
    
    matched_keys = 0
    total_lora_keys = 0

    # Isolate all relevant 'lora_up' keys from the LoRA file
    lora_up_keys = sorted([k for k in lora_weights.keys() if "lora_up.weight" in k and k.startswith("lora_unet_")])
    total_lora_keys = len(lora_up_keys)

    for up_key in lora_up_keys:
        down_key = up_key.replace("lora_up.weight", "lora_down.weight")
        alpha_key = up_key.replace("lora_up.weight", "alpha")

        if down_key not in lora_weights:
            continue

        # --- 1. Translate the key ---
        lora_base_key = up_key.split(".lora_up.weight")[0]
        lora_style_key = lora_base_key[len("lora_unet_"):] + ".weight"
        model_key = translate_lora_key_to_model_key(lora_style_key)
        
        print(f"Processing LoRA layer: '{lora_style_key}'")

        if model_key in weights_with_loras:
            matched_keys += 1
            print(f"  - Match found in base model: '{model_key}'")

            # --- 2. Get original value (Before) ---
            original_value = torch.sum(weights_with_loras[model_key]).item()
            print(f"    - Before: {original_value:.4f}")

            # --- 3. Apply the LoRA update ---
            lora_down = lora_weights[down_key]
            lora_up = lora_weights[up_key]
            
            # Get alpha, default to rank if not present
            rank = lora_down.shape[0]
            alpha = lora_weights.get(alpha_key, torch.tensor(rank)).item()
            
            # Calculate the update, including the alpha scaling
            scale = (alpha / rank) if rank > 0 else 1.0
            update = (lora_up.float() @ lora_down.float()) * scale * LORA_STRENGTH
            
            weights_with_loras[model_key] += update.to(weights_with_loras[model_key].dtype)

            # --- 4. Get new value (After) ---
            modified_value = torch.sum(weights_with_loras[model_key]).item()
            print(f"    - After:  {modified_value:.4f}")
            print("-" * 20)

        else:
            print(f"  - WARNING: No match found in base model for this layer.")
            print("-" * 20)

    print("\n--- Verification Summary ---")
    print(f"Successfully matched and applied {matched_keys} of {total_lora_keys} UNet LoRA layers.")
    print("--- Script Finished ---\n")


Loading base model: flux1-fill-dev-fp8.safetensors

Loading LoRA: comfyui_subject_lora16.safetensors



--- Starting Layer-by-Layer Verification ---

Processing LoRA layer: 'double_blocks_0_img_attn_proj.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_img_attn_qkv.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_img_mlp_0.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_img_mlp_2.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_img_mod_lin.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_txt_attn_proj.weight'
  - WARNING: No match found in base model for this layer.
--------------------
Processing LoRA layer: 'double_blocks_0_txt_attn_qkv.weight'
  - WARNING: No match found in base model for this layer.
